In [1]:
import os
os.listdir()

['smallgray.png',
 '.ipynb_checkpoints',
 '2_cv2_numpyarray_and_images.ipynb',
 '1_Numpy_Basics.ipynb']

# Importing the OpenCV in python

In [2]:
import cv2

## Using "imread" loading an image into a variable

In [6]:
image = cv2.imread('smallgray.png', 0) #0 for grayscale, 1 for bgr

In [7]:
print(image)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [8]:
image_1 = cv2.imread('smallgray.png', 1) #0 for grayscale, 1 for bgr

In [9]:
print(image_1)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


### the object created is a numpy array

In [10]:
type(image)

numpy.ndarray

## Using "imwrite" creating an image using a numpy array
### Returns 'true' if the image is created

In [11]:
cv2.imwrite("anewimage.png", image_1)

True

In [12]:
os.listdir()

['smallgray.png',
 '.ipynb_checkpoints',
 'anewimage.png',
 '2_cv2_numpyarray_and_images.ipynb',
 '1_Numpy_Basics.ipynb']