In [1]:
import os
os.listdir()

['smallgray.png',
 '3_NumpyArray_indexing_slicing_iterating.ipynb',
 '.ipynb_checkpoints',
 'anewimage.png',
 '2_cv2_numpyarray_and_images.ipynb',
 '1_Numpy_Basics.ipynb']

## importing opencv and reading an image into variable

In [2]:
import cv2

image = cv2.imread('smallgray.png',0)

In [3]:
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [4]:
type(image)

numpy.ndarray

# Slicing through the Numpy array

## 1. Getting particular value from the numpy array

In [8]:
image[:2, 2:4] #first the row then the column we need to slice

array([[104, 121],
       [255, 255]], dtype=uint8)

## 2. Getting a single item

In [10]:
image[2,-1] # getting the last item

182

# Itreating through the array

## 1. Getting all the items

In [12]:
for i in image:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


## 2. Getting rows 

In [13]:
for i in image.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


## 3. Getting each value one by one

In [15]:
for i in image.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
