In [8]:
import cv2
import numpy as np
import os
os.listdir()

['smallgray.png',
 '3_NumpyArray_indexing_slicing_iterating.ipynb',
 '4_NumpyArray_Stacking_and_splitting.ipynb',
 '.ipynb_checkpoints',
 'anewimage.png',
 '2_cv2_numpyarray_and_images.ipynb',
 '1_Numpy_Basics.ipynb']

## Creating an array using by reading a image into the image variable

In [4]:
image = cv2.imread('smallgray.png',0)

In [5]:
print(image)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


# For stacking 2 numpy array 

## 1. Stacking horizontally using "numpy.hstack"

In [9]:
image_stack_hor = np.hstack(image,image) # this will fail

TypeError: hstack() takes 1 positional argument but 2 were given

In [10]:
image_stack_hor = np.hstack((image,image)) #except a tuple

In [11]:
print(image_stack_hor)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


## 2. Stacking Vertically using "numpy.vstack"

In [17]:
image_stack_ver = np.vstack((image,image,image))

In [18]:
print(image_stack_ver)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


# For spliting the numpy array

## 1. Spliting horizontaly using "numpy.hsplit"

In [25]:
image_split_hor = np.hsplit(image, 3)

ValueError: array split does not result in an equal division

In [26]:
image_split_hor = np.hsplit(image, 5)

In [27]:
print(image_split_hor)

[array([[187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182]], dtype=uint8)]


## 2. Spliting vertically using "numpy.vsplit"

In [30]:
image_split_ver = np.vsplit(image_stack_ver, 3)

In [31]:
print(image_split_ver)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


In [32]:
type(image_split_ver)

list